language: node_js
node_js:
  - "10"
  - "12"
install:
  - npm install
script:
  - npm run build
  - npm test
after_success:
  - nyc report --reporter=text-lcov > coverage.lcov
  - bash <(curl -s https://codecov.io/bash)